enum DOMManipulationEventEnum {
  MESSAGE_SENT = 'MESSAGE_SENT',
  UPDATED_PROMPT = 'UPDATED_PROMPT',
  CLEAN_PROMPT = 'CLEAN_PROMPT',
  ROLLED_DOWN = 'ROLLED_DOWN',
  STREAM_STARTED = 'STREAM_STARTED',
  STREAM_COMPLETED = 'STREAM_COMPLETED',
  AUDIO_PLAYING = 'AUDIO_PLAYING',
  AUDIO_STOPPED = 'AUDIO_STOPPED',
  CONFIG_UPDATED = 'CONFIG_UPDATED',
  TEXT_TO_SPEECH_UPDATED = 'TEXT_TO_SPEECH_UPDATED',
  MESSAGE_SKIPPED = 'MESSAGE_SKIPPED',
  PLUGIN_STARTED = 'PLUGIN_STARTED',
  VOICES_AVAILABLE = 'VOICES_AVAILABLE',
}

export default DOMManipulationEventEnum;
