export enum IdentifierEnum {
  PREFIX = 'VMGPT',
  PLAYER_COMPONENT_ID = 'VMGPT_PLAYER_COMPONENT_ID',
  PLAYER_COMPONENT_START_ZONE_CN = 'VMGPT_PLAYER_COMPONENT_START_ZONE_CN',
  PLAYER_COMPONENT_START_BUTTON_ID = 'VMGPT_PLAYER_COMPONENT_START_BUTTON_ID',
  PLAYER_COMPONENT_ACTION_BUTTONS_CN = 'VMGPT_PLAYER_COMPONENT_ACTION_BUTTONS_CN',
  PLAYER_COMPONENT_STATUS_BAR_ID = 'VMGPT_PLAYER_COMPONENT_STATUS_BAR_ID',
  PLAYER_COMPONENT_SUSPENDED_AREA_ID = 'VMGPT_PLAYER_COMPONENT_SUSPENDED_AREA_ID',
  PLAYER_COMPONENT_RESUME_BUTTON_ID = 'VMGPT_PLAYER_COMPONENT_RESUME_BUTTON_ID',
}
