enum RecognitionEventEnum {
  UPDATE_TRANSCRIPT = 'UPDATE_TRANSCRIPT',
  UPDATE_MICROPHONE_VOLUME = 'UPDATE_MICROPHONE_VOLUME',
  UPDATE_IS_LISTENING = 'UPDATE_IS_LISTENING',
  UPDATE_ERROR = 'UPDATE_ERROR',
}

export default RecognitionEventEnum;
